{
 "title": "Prometheus Grafana Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(request_processing_seconds{endpoint=\"/classify_image\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(request_processing_seconds{endpoint=\"/feedback_class\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(request_processing_seconds{endpoint=\"/extend_dataset\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(counter_feedback_total[1m])",
     "legendFormat": "Feedbacks"
    },
    {
     "expr": "rate(counter_labeled_images_total[1m])",
     "legendFormat": "New labeled images"
    },
    {
     "expr": "rate(counter_predictions_total[1m])",
     "legendFormat": "Predictions"
    }
   ]
  },
  {
   "title": "API usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "counter_feedback_total", "legendFormat": "Feedbacks" },
    { "expr": "counter_labeled_images_total", "legendFormat": "New labeled images" },
    { "expr": "counter_predictions_total", "legendFormat": "Predictions" }
   ]
  },
  {
   "title": "Image Size Histogram",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "img_size_bucket", "legendFormat": "__auto" }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 2, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler!=\"/metrics\", method!=\"OPTIONS\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"fastapi\"}[1m])",
     "legendFormat": "Time percentage"
    }
   ]
  },
  {
   "title": "Virtual memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_virtual_memory_bytes{instance=\"docker.for.mac.localhost:9100\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Occupied memory ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "img_size_sum", "legendFormat": "__auto" }
   ]
  },
  { "title": "Drift Detector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Average Detection Delay Following Change",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_ddfc", "legendFormat": "__auto" }
   ]
  }
 ]
}