{
 "title": "Prometheus Grafana Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(counter_feedback_total[1m])",
     "legendFormat": "Feedbacks"
    },
    {
     "expr": "rate(counter_labeled_images_total[1m])",
     "legendFormat": "New labeled images"
    },
    {
     "expr": "rate(counter_predictions_total[1m])",
     "legendFormat": "Predictions"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler!=\"/metrics\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "counter_feedback_total", "legendFormat": "Feedbacks" },
    { "expr": "counter_labeled_images_total", "legendFormat": "New labeled images" },
    { "expr": "counter_predictions_total", "legendFormat": "Predictions" }
   ]
  },
  {
   "title": "Memory Occupied",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "img_size_sum", "legendFormat": "__auto" }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"fastapi\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_virtual_memory_bytes{instance=\"docker.for.mac.localhost:9100\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}