global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus_api
    static_configs:
      - targets: ['docker.for.mac.localhost:9000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: docker.for.mac.localhost:9000