learning_rate : 0.005
momentum : 0.9
label_smoothing : 0.1
dropout_rate : 0.4
l2 : 0.005
batch_size : 32
epochs : 1
algorithm: "Stochastic Gradient Descent"
loss: "Categorical-Cross-Entropy"
patience: 5
early_stopping_metric: 'val_loss'