name: api_testing_workflow

on:
  push:
    branches:
      - 'development'
    paths:
      - 'src/api/**'
  
jobs:
  api-testing:
    name: API testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.9.16
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.16"   
          cache: 'pip'  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test the quality of the API code with pylint
        run: |
          pylint --fail-under=7 src/api
      - name: Test the API with pytest
        run: |
          pytest src/api/test_server.py
